import frappe
from frappe.tests.utils import FrappeTestCase


class TestOrganizationModel(FrappeTestCase):
    def test_slug_autogenerated_from_name(self):
        org = frappe.get_doc({
            "doctype": "WebODM Organization",
            "organization_name": "Acme Survey Co",
        }).insert(ignore_permissions=True)
        self.assertEqual(org.slug, "acme-survey-co")
        self.assertEqual(org.status, "Active")

    def test_slug_is_unique(self):
        frappe.get_doc({"doctype": "WebODM Organization",
                        "organization_name": "Dupe One", "slug": "dupe"}).insert(ignore_permissions=True)
        with self.assertRaises(frappe.exceptions.ValidationError):
            frappe.get_doc({"doctype": "WebODM Organization",
                            "organization_name": "Dupe Two", "slug": "dupe"}).insert(ignore_permissions=True)
